[package]
name = "docsearch_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
url = "2.3.1"
voyager = "0.2.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3.26"
urlencoding = "2.1.2"
